<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HP" name="calculator.MathFunctions" tests="10" failures="1" timestamp="2020-07-02T08:48:29 IST" time="0.101" errors="0">
  <testcase name="addd" time="0.015" classname="calculator.MathFunctions"/>
  <system-out/>
  <testcase name="exp" time="0.000" classname="calculator.MathFunctions"/>
  <system-out>
The power value is : 3025.6672459330484  </system-out>
  <testcase name="exp" time="0.000" classname="calculator.MathFunctions"/>
  <system-out>
The power value is : 2.909595305722029E46  </system-out>
  <testcase name="inverse" time="0.006" classname="calculator.MathFunctions">
    <failure type="java.lang.AssertionError" message="did not expect [-5] but found [-5]">
      <![CDATA[java.lang.AssertionError: did not expect [-5] but found [-5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertNotEquals(Assert.java:1399)
at org.testng.Assert.assertNotEquals(Assert.java:1404)
at calculator.MathFunctions.inverse(MathFunctions.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- inverse -->
  <system-out/>
  <testcase name="mod" time="0.016" classname="calculator.MathFunctions"/>
  <system-out>
The modulus value is: 9  </system-out>
  <testcase name="mod" time="0.000" classname="calculator.MathFunctions"/>
  <system-out>
The modulus value is: 0  </system-out>
  <testcase name="exp" time="0.032" classname="calculator.MathFunctions"/>
  <system-out>
The power value is : 2.1710862763428168E13  </system-out>
  <testcase name="mod" time="0.016" classname="calculator.MathFunctions"/>
  <system-out>
The modulus value is: 6  </system-out>
  <testcase name="addd" time="0.000" classname="calculator.MathFunctions"/>
  <system-out/>
  <testcase name="addd" time="0.016" classname="calculator.MathFunctions"/>
  <system-out/>
</testsuite> <!-- calculator.MathFunctions -->
